# Aqui terá as configurações do nosso banco dados H2 Database
# DATASOURCE
spring.datasource.driverClassName=org.h2.Driver
# String de conexão com o banco de dados
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 CLIENT, h2 habilitado no console
spring.h2.console.enabled=true
# Caminho da url para acessar o H2 Database
spring.h2.console.path=/h2-console
# JPA, SQL,
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
# Essas configurações mostram os comandos SQL que foram executados no console do java
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true